version: '3.8'

services:
  web_server:
    build:
      context: .
      dockerfile: ./Dockerfile_server
    env_file:
      - .env
    ports:
      - "127.0.0.1:5000:5000"
    restart: on-failure
    volumes:
      - api_server:/app/
    depends_on:
      - dbpostgres

    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - sanedge

  web_client:
    build:
      context: .
      dockerfile: ./Dockerfile_client
    env_file:
      - .env
    ports:
      - "127.0.0.1:5001:5001"
    restart: on-failure
    volumes:
      - api_client:/app/
    depends_on:
      - dbpostgres
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

    networks:
      - sanedge

  dbpostgres:
    image: postgres:15.5-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - sanedge
    restart: unless-stopped

volumes:
  api_server:
  api_client:
  database:


networks:
  sanedge:
    driver: bridge
