// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: sale.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SaleServiceClient is the client API for SaleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SaleServiceClient interface {
	CreateSale(ctx context.Context, in *CreateSaleInput, opts ...grpc.CallOption) (*SaleResponse, error)
	GetSales(ctx context.Context, in *SalesRequest, opts ...grpc.CallOption) (*SalesResponse, error)
	GetSale(ctx context.Context, in *SaleRequest, opts ...grpc.CallOption) (*SaleResponse, error)
	UpdateSale(ctx context.Context, in *UpdateSaleInput, opts ...grpc.CallOption) (*SaleResponse, error)
	DeleteSale(ctx context.Context, in *SaleRequest, opts ...grpc.CallOption) (*DeleteSaleResponse, error)
}

type saleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSaleServiceClient(cc grpc.ClientConnInterface) SaleServiceClient {
	return &saleServiceClient{cc}
}

func (c *saleServiceClient) CreateSale(ctx context.Context, in *CreateSaleInput, opts ...grpc.CallOption) (*SaleResponse, error) {
	out := new(SaleResponse)
	err := c.cc.Invoke(ctx, "/pb.SaleService/CreateSale", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saleServiceClient) GetSales(ctx context.Context, in *SalesRequest, opts ...grpc.CallOption) (*SalesResponse, error) {
	out := new(SalesResponse)
	err := c.cc.Invoke(ctx, "/pb.SaleService/GetSales", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saleServiceClient) GetSale(ctx context.Context, in *SaleRequest, opts ...grpc.CallOption) (*SaleResponse, error) {
	out := new(SaleResponse)
	err := c.cc.Invoke(ctx, "/pb.SaleService/GetSale", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saleServiceClient) UpdateSale(ctx context.Context, in *UpdateSaleInput, opts ...grpc.CallOption) (*SaleResponse, error) {
	out := new(SaleResponse)
	err := c.cc.Invoke(ctx, "/pb.SaleService/UpdateSale", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saleServiceClient) DeleteSale(ctx context.Context, in *SaleRequest, opts ...grpc.CallOption) (*DeleteSaleResponse, error) {
	out := new(DeleteSaleResponse)
	err := c.cc.Invoke(ctx, "/pb.SaleService/DeleteSale", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SaleServiceServer is the server API for SaleService service.
// All implementations must embed UnimplementedSaleServiceServer
// for forward compatibility
type SaleServiceServer interface {
	CreateSale(context.Context, *CreateSaleInput) (*SaleResponse, error)
	GetSales(context.Context, *SalesRequest) (*SalesResponse, error)
	GetSale(context.Context, *SaleRequest) (*SaleResponse, error)
	UpdateSale(context.Context, *UpdateSaleInput) (*SaleResponse, error)
	DeleteSale(context.Context, *SaleRequest) (*DeleteSaleResponse, error)
	mustEmbedUnimplementedSaleServiceServer()
}

// UnimplementedSaleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSaleServiceServer struct {
}

func (UnimplementedSaleServiceServer) CreateSale(context.Context, *CreateSaleInput) (*SaleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSale not implemented")
}
func (UnimplementedSaleServiceServer) GetSales(context.Context, *SalesRequest) (*SalesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSales not implemented")
}
func (UnimplementedSaleServiceServer) GetSale(context.Context, *SaleRequest) (*SaleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSale not implemented")
}
func (UnimplementedSaleServiceServer) UpdateSale(context.Context, *UpdateSaleInput) (*SaleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSale not implemented")
}
func (UnimplementedSaleServiceServer) DeleteSale(context.Context, *SaleRequest) (*DeleteSaleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSale not implemented")
}
func (UnimplementedSaleServiceServer) mustEmbedUnimplementedSaleServiceServer() {}

// UnsafeSaleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SaleServiceServer will
// result in compilation errors.
type UnsafeSaleServiceServer interface {
	mustEmbedUnimplementedSaleServiceServer()
}

func RegisterSaleServiceServer(s grpc.ServiceRegistrar, srv SaleServiceServer) {
	s.RegisterService(&SaleService_ServiceDesc, srv)
}

func _SaleService_CreateSale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSaleInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaleServiceServer).CreateSale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SaleService/CreateSale",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaleServiceServer).CreateSale(ctx, req.(*CreateSaleInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _SaleService_GetSales_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SalesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaleServiceServer).GetSales(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SaleService/GetSales",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaleServiceServer).GetSales(ctx, req.(*SalesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SaleService_GetSale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaleServiceServer).GetSale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SaleService/GetSale",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaleServiceServer).GetSale(ctx, req.(*SaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SaleService_UpdateSale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSaleInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaleServiceServer).UpdateSale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SaleService/UpdateSale",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaleServiceServer).UpdateSale(ctx, req.(*UpdateSaleInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _SaleService_DeleteSale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaleServiceServer).DeleteSale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SaleService/DeleteSale",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaleServiceServer).DeleteSale(ctx, req.(*SaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SaleService_ServiceDesc is the grpc.ServiceDesc for SaleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SaleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SaleService",
	HandlerType: (*SaleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSale",
			Handler:    _SaleService_CreateSale_Handler,
		},
		{
			MethodName: "GetSales",
			Handler:    _SaleService_GetSales_Handler,
		},
		{
			MethodName: "GetSale",
			Handler:    _SaleService_GetSale_Handler,
		},
		{
			MethodName: "UpdateSale",
			Handler:    _SaleService_UpdateSale_Handler,
		},
		{
			MethodName: "DeleteSale",
			Handler:    _SaleService_DeleteSale_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sale.proto",
}
