// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: supplier.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SupplierServiceClient is the client API for SupplierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SupplierServiceClient interface {
	CreateSupplier(ctx context.Context, in *CreateSupplierInput, opts ...grpc.CallOption) (*SupplierResponse, error)
	GetSuppliers(ctx context.Context, in *SuppliersRequest, opts ...grpc.CallOption) (*SuppliersResponse, error)
	GetSupplier(ctx context.Context, in *SupplierRequest, opts ...grpc.CallOption) (*SupplierResponse, error)
	UpdateSupplier(ctx context.Context, in *UpdateSupplierInput, opts ...grpc.CallOption) (*SupplierResponse, error)
	DeleteSupplier(ctx context.Context, in *SupplierRequest, opts ...grpc.CallOption) (*DeleteSupplierResponse, error)
}

type supplierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSupplierServiceClient(cc grpc.ClientConnInterface) SupplierServiceClient {
	return &supplierServiceClient{cc}
}

func (c *supplierServiceClient) CreateSupplier(ctx context.Context, in *CreateSupplierInput, opts ...grpc.CallOption) (*SupplierResponse, error) {
	out := new(SupplierResponse)
	err := c.cc.Invoke(ctx, "/pb.SupplierService/CreateSupplier", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierServiceClient) GetSuppliers(ctx context.Context, in *SuppliersRequest, opts ...grpc.CallOption) (*SuppliersResponse, error) {
	out := new(SuppliersResponse)
	err := c.cc.Invoke(ctx, "/pb.SupplierService/GetSuppliers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierServiceClient) GetSupplier(ctx context.Context, in *SupplierRequest, opts ...grpc.CallOption) (*SupplierResponse, error) {
	out := new(SupplierResponse)
	err := c.cc.Invoke(ctx, "/pb.SupplierService/GetSupplier", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierServiceClient) UpdateSupplier(ctx context.Context, in *UpdateSupplierInput, opts ...grpc.CallOption) (*SupplierResponse, error) {
	out := new(SupplierResponse)
	err := c.cc.Invoke(ctx, "/pb.SupplierService/UpdateSupplier", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierServiceClient) DeleteSupplier(ctx context.Context, in *SupplierRequest, opts ...grpc.CallOption) (*DeleteSupplierResponse, error) {
	out := new(DeleteSupplierResponse)
	err := c.cc.Invoke(ctx, "/pb.SupplierService/DeleteSupplier", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SupplierServiceServer is the server API for SupplierService service.
// All implementations must embed UnimplementedSupplierServiceServer
// for forward compatibility
type SupplierServiceServer interface {
	CreateSupplier(context.Context, *CreateSupplierInput) (*SupplierResponse, error)
	GetSuppliers(context.Context, *SuppliersRequest) (*SuppliersResponse, error)
	GetSupplier(context.Context, *SupplierRequest) (*SupplierResponse, error)
	UpdateSupplier(context.Context, *UpdateSupplierInput) (*SupplierResponse, error)
	DeleteSupplier(context.Context, *SupplierRequest) (*DeleteSupplierResponse, error)
	mustEmbedUnimplementedSupplierServiceServer()
}

// UnimplementedSupplierServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSupplierServiceServer struct {
}

func (UnimplementedSupplierServiceServer) CreateSupplier(context.Context, *CreateSupplierInput) (*SupplierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSupplier not implemented")
}
func (UnimplementedSupplierServiceServer) GetSuppliers(context.Context, *SuppliersRequest) (*SuppliersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSuppliers not implemented")
}
func (UnimplementedSupplierServiceServer) GetSupplier(context.Context, *SupplierRequest) (*SupplierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSupplier not implemented")
}
func (UnimplementedSupplierServiceServer) UpdateSupplier(context.Context, *UpdateSupplierInput) (*SupplierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSupplier not implemented")
}
func (UnimplementedSupplierServiceServer) DeleteSupplier(context.Context, *SupplierRequest) (*DeleteSupplierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSupplier not implemented")
}
func (UnimplementedSupplierServiceServer) mustEmbedUnimplementedSupplierServiceServer() {}

// UnsafeSupplierServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SupplierServiceServer will
// result in compilation errors.
type UnsafeSupplierServiceServer interface {
	mustEmbedUnimplementedSupplierServiceServer()
}

func RegisterSupplierServiceServer(s grpc.ServiceRegistrar, srv SupplierServiceServer) {
	s.RegisterService(&SupplierService_ServiceDesc, srv)
}

func _SupplierService_CreateSupplier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSupplierInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).CreateSupplier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SupplierService/CreateSupplier",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).CreateSupplier(ctx, req.(*CreateSupplierInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierService_GetSuppliers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuppliersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).GetSuppliers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SupplierService/GetSuppliers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).GetSuppliers(ctx, req.(*SuppliersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierService_GetSupplier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupplierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).GetSupplier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SupplierService/GetSupplier",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).GetSupplier(ctx, req.(*SupplierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierService_UpdateSupplier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSupplierInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).UpdateSupplier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SupplierService/UpdateSupplier",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).UpdateSupplier(ctx, req.(*UpdateSupplierInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierService_DeleteSupplier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupplierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).DeleteSupplier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SupplierService/DeleteSupplier",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).DeleteSupplier(ctx, req.(*SupplierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SupplierService_ServiceDesc is the grpc.ServiceDesc for SupplierService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SupplierService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SupplierService",
	HandlerType: (*SupplierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSupplier",
			Handler:    _SupplierService_CreateSupplier_Handler,
		},
		{
			MethodName: "GetSuppliers",
			Handler:    _SupplierService_GetSuppliers_Handler,
		},
		{
			MethodName: "GetSupplier",
			Handler:    _SupplierService_GetSupplier_Handler,
		},
		{
			MethodName: "UpdateSupplier",
			Handler:    _SupplierService_UpdateSupplier_Handler,
		},
		{
			MethodName: "DeleteSupplier",
			Handler:    _SupplierService_DeleteSupplier_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "supplier.proto",
}
